type Query {
    recipe(id: ID): Recipe
    pid: Int
}

type Recipe {
    id: ID!
    name: String
    steps: String
    ingredients: [Ingredient]!
}

# !表示必填字段
type Ingredient {
    id: ID!
    name: String!
    quantity: String
}
